// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTqDPlfb_zAoGQLEHKQEVgBNpRsx7ZqS4',
    appId: '1:73448188605:web:953fd99359b2d777b9e5d4',
    messagingSenderId: '73448188605',
    projectId: 'bookshopapp-6c0fb',
    authDomain: 'bookshopapp-6c0fb.firebaseapp.com',
    storageBucket: 'bookshopapp-6c0fb.firebasestorage.app',
    measurementId: 'G-F90BTWJ2HW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJPEGyw4vukF9PvZkhFcSo0eFJod6VyQ',
    appId: '1:73448188605:android:fc0367e5b6f43ed5b9e5d4',
    messagingSenderId: '73448188605',
    projectId: 'bookshopapp-6c0fb',
    storageBucket: 'bookshopapp-6c0fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXTVn6x3ReQFj7_nZ-V7Ue4ZbFfhI_gsE',
    appId: '1:73448188605:ios:94fba0a9c0741fc1b9e5d4',
    messagingSenderId: '73448188605',
    projectId: 'bookshopapp-6c0fb',
    storageBucket: 'bookshopapp-6c0fb.firebasestorage.app',
    iosBundleId: 'com.example.bookshopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXTVn6x3ReQFj7_nZ-V7Ue4ZbFfhI_gsE',
    appId: '1:73448188605:ios:94fba0a9c0741fc1b9e5d4',
    messagingSenderId: '73448188605',
    projectId: 'bookshopapp-6c0fb',
    storageBucket: 'bookshopapp-6c0fb.firebasestorage.app',
    iosBundleId: 'com.example.bookshopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTqDPlfb_zAoGQLEHKQEVgBNpRsx7ZqS4',
    appId: '1:73448188605:web:ea074e7652caeda1b9e5d4',
    messagingSenderId: '73448188605',
    projectId: 'bookshopapp-6c0fb',
    authDomain: 'bookshopapp-6c0fb.firebaseapp.com',
    storageBucket: 'bookshopapp-6c0fb.firebasestorage.app',
    measurementId: 'G-MMH7KHBGTC',
  );
}
